name: OpPermissions 
main: me.OpPermissions.OpPermissionsMainClass 
version: 1.0.3.1
description: A plugin helping with op permissions  
author: aappleton3 
database: false 
commands: 
  opset:
    description: Add or remove someone to the list of permanent ops 
    usage: /opset add|remove|list|version|{help [all|config] [1|2|3]}|check|{config <action> [field]} [playername|data] 
    permission-message: You do not have the required permissions to perform this command 
  oppermissions:
    description: The command to show help for this plugin 
    usage: /oppermissions 
    permission-message: You do not have the required permissions to perform this command 
  oplist:
    description: The command to list all the ops on the server
    usage: /oplist [online|offline|both] 
    permission-message: You do not have the required permissions to perform this command 
  oprequest:
    description: The command to send a request to the ops 
    usage: /oprequest <message>
    permission-message: You do not have the required permissions to perform this command 
  opcommand:
    description: The command to add and remove blocked commands 
    usage: /opcommand {add|remove|check <command>}|list 
    permission-message: You do not have the required permissions to perform this command 
  opbancommands:
    description: The command to add and remove blocked ban commands for ops 
    usage: /opbancommands {add|remove|check <command>}|list
    permission-message: You do not have the required permissions to perform this command 
permissions: 
  oppermissions.*:
    description: Add or remove players to the permanent ops list 
    default: false
    children:
      oppermissions.read.*: true
      oppermissions.add: true
      oppermissions.remove: true
      oppermissions.config.*: true
      oppermissions.op: true
      oppermissions.deop: true
      oppermissions.oplist.*: true
      oppermissions.showallhelp: true
      oppermissions.oprequest.*: true
      oppermissions.seepluginmessages: true
      oppermissions.commands.*: true
      oppermissions.showopattempts: true
      oppermissions.ban.*: true
      oppermissions.opbancommands.*: true
  oppermissions.read.*:
    description: List and check the permanent ops 
    default: op
    children:
      oppermissions.read.list: true
      oppermissions.read.check: true
  oppermissions.read.list:
    description: List the permanent ops 
    default: op
  oppermissions.read.check:
    description: Check if a player is a permanent op 
    default: op
  oppermissions.add:
    description: Add a permanent op to the list 
    default: false
  oppermissions.remove:
    description: Remove a permanent op from the list
    default: false 
  oppermissions.config.*: 
    description: Change the config file 
    default: false
    children:
      oppermissions.config.save: true
      oppermissions.config.reload: true
      oppermissions.config.set.*: true
      oppermissions.config.updateplayeruuids: true
  oppermissions.config.save:
    description: Save the configuration 
    default: false
  oppermissions.config.reload:
    description: Reload the configuration 
    default: false
  oppermissions.config.set.*:
    description: Set config values 
    default: false 
    children:
      oppermissions.config.set.opscanop: true
      oppermissions.config.set.opscandeop: true
      oppermissions.config.set.allowrequests: true
      oppermissions.config.set.useuuids: true
      oppermissions.config.set.updateonplayerjoins: true
      oppermissions.config.set.onlyautoupdateonline: true
      oppermissions.config.set.allowunsafechanges: true
      oppermissions.config.set.announceops: true
      oppermissions.config.set.permanentopsusecommands: true
      oppermissions.config.set.showopattempts: true
      oppermissions.config.set.showcommanduse: true
      oppermissions.config.set.bannableops: true
      oppermissions.config.set.bannablepermanentops: true
      oppermissions.config.set.deoponban: true
      oppermissions.config.set.showbanattempts: true
  oppermissions.config.set.opscanop:
    description: Set the value of the opscanop field of the config file 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.opscandeop:
    description: Set the value of the opscandeop field of the config file 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.allowrequests:
    description: Set the value of the allowrequests field on the config file 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.useuuids:
    description: Set whether the plugin should store usernames or UUIDs 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.updateonplayerjoins:
    description: Set whether the plugin should check the information of players when they join 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.onlyautoupdateonline:
    description: Set whether the plugin should only allow updates to online players or not 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.announceops:
    description: Send a message to all players when an op joins 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.permanentopsusecommands:
    description: Let permanent ops use all blocked commands 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.showopattempts:
    description: Notify the player every time someone uses the /op or /deop commands 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.showcommanduse:
    description: Notify the player evey time someone uses one of the commands on the blocked command list 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.bannableops:
    description: Let the player ban ops 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.bannablepermanentops:
    description: Let the player ban permanent ops 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.deoponban:
    description: Make the plugin deop ops who get banned 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.showbanattempts:
    description: Let the player see op ban attempts, even if they are unsuccessful
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.showallhelp:
    description: Can see help for commands the player does not have permission to use 
    default: op
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.seedetailedsethelp:
    description: Enable the player to see help for setting each config field 
    default: false
  oppermissions.config.verifylist:
    description: Enable the player to update names and UUIDs stored in the config 
    default: false
  oppermissions.op:
    description: Can op a player, depending on the config file 
    default: false
  oppermissions.deop:
    description: Can deop a player, depending on the config file 
    default: false
  oppermissions.oplist.*:
    description: Get a list of all online and offline server ops 
    default: op
    children:
      oppermissions.oplist.online: true
      oppermissions.oplist.offline: true
  oppermissions.oplist.online:
    description: Can get a list of all online server ops 
    default: op
  oppermissions.oplist.offline:
    description: Can get a list of all offline ops 
    default: op
  oppermissions.oprequest.*:
    description: Can send and receive op request messages 
    default: op
    children:
      oppermissions.oprequest.send: true
      oppermissions.oprequest.receive: true
  oppermissions.oprequest.send:
    description: Can send op request messages 
    default: op
  oppermissions.oprequest.receive:
    description: Can see op request messages 
    default: op
  oppermissions.seepluginmessages:
    description: Can see plugin messages (such as config saved messages) 
    default: op
  oppermissions.commands.*:
    description: The root command to add and remove blocked commands
    default: false
    children:
      oppermissions.commands.add: true
      oppermissions.commands.remove: true
      oppermissions.commands.list: true
      oppermissions.commands.check: true
      oppermissions.commands.command: true
      oppermissions.commands.show: true
  oppermissions.commands.add:
    description: Add a new blocked command 
    default: false
  oppermissions.commands.remove:
    description: remove a blocked command 
    default: false
  oppermissions.commands.list:
    description: List the blocked commands 
    default: false
  oppermissions.commands.check:
    description: Check if a command is blocked 
    default: false
  oppermissions.commands.command:
    description: Perform the blocked commands 
    default: false
  oppermissions.commands.show:
    description: Be notified every time someone tries to use (even if unsuccessfully) one of the commands on the blocked command list 
    default: false
  oppermissions.showopattempts:
    description: Be notified every time someone tries to use (even if unsuccessfully) the /op or /deop command 
    default: false
  oppermissions.ban.*:
    description: Ban all ops and permanent ops, depending non the config file 
    default: false
    children:
      oppermissions.ban.permanentops: true
      oppermissions.ban.show: true
  oppermissions.ban.permanentops: 
    description: Ban permanent ops depending on the config file 
    default: false
    children:
      oppermissions.ban.ops: true
  oppermissions.ban.ops:
    description: Ban ops depending on the config file 
    default: false
  oppermissions.ban.show:
    description: Be notified every time someone tries to use (even if unsuccessfully) one of the ban commands on an op 
    default: false
  oppermissions.opbancommands.*:
    description: The root command to add and remove blocked commands
    default: false
    children:
      oppermissions.opbancommands.add: true
      oppermissions.opbancommands.remove: true
      oppermissions.opbancommands.list: true
      oppermissions.opbancommands.check: true
  oppermissions.opbancommands.add:
    description: Add a new watched ban command 
    default: false
  oppermissions.opbancommands.remove:
    description: Remove a watched ban command 
    default: false
  oppermissions.opbancommands.list:
    description: List the watched ban commands 
    default: false
  oppermissions.opbancommands.check:
    description: Check if a command is watched ban command 
    default: false
