name: OpPermissions 
main: me.OpPermissions.OpPermissionsMainClass 
version: Alpha_0.1.2.3  
description: A plugin helping with op permissions  
author: aappleton3 
database: false 
commands: 
  opset:
    description: Add or remove someone to the list of permenant ops 
    usage: /opset <add|remove|list|version|help [all|config] [1|2]|check|config <action> [field]> [playername|data] 
    permission-message: You do not have the required permissions to perform this command 
  oppermissions:
    description: The command to show help for this plugin 
    usage: /oppermissions 
    permission-message: You do not have the required permissions to perform this command 
  oplist:
    description: The command to list all the ops on the server
    usage: /oplist [online|offline|both] 
    permission-message: You do not have the required permissions to perform this command 
  oprequest:
    description: The command to send a request to the ops 
    usage: /oprequest <message>
    permission-message: You do not have the required permissions to perform this command 
permissions: 
  oppermissions.*:
    description: Add or remove players to the permenant ops list 
    default: false
    children:
      oppermissions.read.*: true
      oppermissions.add: true
      oppermissions.remove: true
      oppermissions.config.*: true
      oppermissions.op: true
      oppermissions.oplist.*: true
      oppermissions.showallhelp: true
      oppermissions.oprequest.*: true
      oppermissions.seepluginmessages: true
  oppermissions.read.*:
    description: List and check the permenant ops 
    default: op
    children:
      oppermissions.read.list: true
      oppermissions.read.check: true
  oppermissions.read.list:
    description: List the permenant ops 
    default: op
  oppermissions.read.check:
    description: Check if a player is a permenant op 
    default: op
  oppermissions.add:
    description: Add a permenant op to the list 
    default: false
  oppermissions.remove:
    description: Remove a permenant op from the list
    default: false 
  oppermissions.config.*: 
    description: Change the config file 
    default: false
    children:
      oppermissions.config.save: true
      oppermissions.config.reload: true
      oppermissions.config.set.*: true
      oppermissions.config.updateplayeruuids: true
  oppermissions.config.save:
    description: Save the configuration 
    default: false
  oppermissions.config.reload:
    description: Reload the configuration 
    default: false
  oppermissions.config.set.*:
    description: Set config values 
    default: false 
    children:
      oppermissions.config.set.opscanop: true
      oppermissions.config.set.allowrequests: true
      oppermissions.config.set.useuuids: true
      oppermissions.config.set.updateonplayerjoins: true
      oppermissions.config.set.onlyautoupdateonline: true
      oppermissions.config.set.allowunsafechanges: true
  oppermissions.config.set.opscanop:
    description: Set the value of the opscanop field of the config file 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.allowrequests:
    description: Set the value of the allowrequests field on the config file 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.useuuids:
    description: Set whether the plugin should store usernames or UUIDs 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.updateonplayerjoins:
    description: Set whether the plugin should check the information of players when they join 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.set.onlyautoupdateonline:
    description: Set whether the plugin should only allow updates to online players or not 
    default: false
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.showallhelp:
    description: Can see help for commands the player does not have permission to use 
    default: op
    children:
      oppermissions.config.seedetailedsethelp: true
  oppermissions.config.seedetailedsethelp:
    description: Enable the player to see help for setting each config field 
    default: false
  oppermissions.config.updateplayeruuids:
    description: Enable the player to update names and UUIDs stored in the config 
    default: false
  oppermissions.op:
    description: Can op a player, depending on the config file 
    default: false
  oppermissions.oplist.*:
    description: Get a list of all online and offline server ops 
    default: op
    children:
      oppermissions.oplist.online: true
      oppermissions.oplist.offline: true
  oppermissions.oplist.online:
    description: Can get a list of all online server ops 
    default: op
  oppermissions.oplist.offline:
    description: Can get a list of all offline ops 
    default: op
  oppermissions.oprequest.*:
    description: Can send and receive op request messages 
    default: op
    children:
      oppermissions.oprequest.send: true
      oppermissions.oprequest.receive: true
  oppermissions.oprequest.send:
    description: Can send op request messages 
    default: op
  oppermissions.oprequest.receive:
    description: Can see op request messages 
    default: op
  oppermissions.seepluginmessages:
    description: Can see plugin messages (such as config saved messages) 
    default: op
