name: OpPermissions 
main: me.OpPermissions.OpPermissionsMainClass 
version: development_0.1.0.0  
description: A plugin helping with op permissions  
author: aappleton3 
database: false 
commands: 
  opset:
    description: Add or remove someone to the list of permenant ops 
    usage: /opset <add|remove|list|version|help|check|config <action>> [playername|data] 
    permission-message: You do not have the required permissions to perform this command 
  oppermissions:
    description: The command to show help for this plugin 
    usage: /oppermissions 
    permission-message: You do not have the required permissions to perform this command 
  oplist:
    description: The command to list all the ops on the server
    usage: /oplist
    permission-message: You do not have the required permissions to perform this command 
permissions: 
  oppermissions.*:
    description: Add or remove players to the permenant ops list 
    default: false
    children:
      oppermissions.read.*: true
      oppermissions.add: true
      oppermissions.remove: true
      oppermissions.save: true
      oppermissions.reload: true
      oppermissions.setcanop: true
      oppermissions.op: true
      oppermissions.ops: true
  oppermissions.read.*:
    description: List and check the permenant ops 
    default: op
    children:
      oppermissions.read.list: true
      oppermissions.read.check: true
  oppermissions.read.list:
    description: List the permenant ops 
    default: op
  oppermissions.read.check:
    description: Check if a player is a permenant op 
    default: op
  oppermissions.add:
    description: Add a permenant op to the list 
    default: false
  oppermissions.remove:
    description: Remove a permenant op from the list
    default: false 
  oppermissions.save:
    description: Save the configuration 
    default: false
  oppermissions.reload:
    description: Reload the configuration 
    default: false
  oppermissions.setcanop:
    description: Set the value of the opscanop field of the config file 
    default: false
  oppermissions.op:
    description: Can op a player, depending on the config file 
    default: false
  oppermissions.ops:
    description: Get a list of all server ops 
    default: op
