useuuids: true
updateonplayerjoins: true
onlyautoupdateonline: true
allowrequests: both
opscanop: default
opscandeop: default
announceops: no
showopattempts: true
permanentopsusecommands: true
showcommanduse: true
ops: []
commands: []

