useuuids: true
updateonplayerjoins: true
onlyautoupdateonline: true
allowrequests: both
opscanop: default
opscandeop: default
announceops: no
showopattempts: true
permanentopsusecommands: true
showcommanduse: true
bannableops: default
bannablepermanentops: default
deoponban: false
showbanattempts: true
ops: []
commands: []
opbancommands:
- ban ([a-zA-Z0-9_]+)
- tempban ([a-zA-Z0-9_]+) .+
- kick ([a-zA-Z0-9_]+)
- blacklist ([a-zA-Z0-9_]+)
- ip\-ban ([a-zA-Z0-9_]+)
- ipban ([a-zA-Z0-9_]+)
- ban\-ip ([a-zA-Z0-9_]+)
- banip ([a-zA-Z0-9_]+)

